export { MainPage } from './src/main/ets/components/MainPage'

export { TestPage } from './src/main/ets/components/TestPage'

export { init } from './src/main/ets/manage/HmVideoPlayer'

export { play } from './src/main/ets/manage/HmVideoPlayer'

export { pause } from './src/main/ets/manage/HmVideoPlayer'

export { resume } from './src/main/ets/manage/HmVideoPlayer'

export { stop } from './src/main/ets/manage/HmVideoPlayer'

export { release } from './src/main/ets/manage/HmVideoPlayer'

export { getDuration } from './src/main/ets/manage/HmVideoPlayer'

export { onStateChange } from './src/main/ets/manage/HmVideoPlayer'

export { onTimeUpdate } from './src/main/ets/manage/HmVideoPlayer'

export { ratePlay } from './src/main/ets/manage/HmVideoPlayer'

export { seek } from './src/main/ets/manage/HmVideoPlayer'
