#ifndef HMVIDEOPLAYER_STATECODE_H
#define HMVIDEOPLAYER_STATECODE_H

enum StateCode {
    INIT_STATE = 1,
    PREPARED_STATE,
    PLAYING_STATE,
    PAUSED_STATE,
    COMPLETED_STATE,
    STOPPED_STATE,
    RELEASE_STATE,
    ERROR_STATE
};
#endif // HMVIDEOPLAYER_STATECODE_H
